### ISSUE TITLE
no data displayed

### ISSUE THREAD

**Issue by juniur** [avatsaev/angular-contacts-app-example#12]
i tried running the backend and the client and no data displayed on the browser.

**Comment by avatsaev** [comment]
how did you run it?

**Comment by juniur** [comment]
i downloaded the backend and run the instruction: npm install && node .  once the server running, i go to client folder and execute: npm start, on the browser i paste the localhost:4200 then no data displayed on the browser. before it was running, after the changes this problem occurred.

**Comment by juniur** [comment]
i downloaded the backend (angular-contacts-app-example-api)
and run this command: npm install && node . Once the server is running i go to frontend (angular-contacts-app-example) and execute this: npm start. i paste localhost:4200 to the browser address bar and to my surprise no data displayed. before i don't have this problem, i noticed that it occurred after the updates have been made. thanks.

**Comment by avatsaev** [comment]
if you have docker and docker-compose installed all you have to do is run `docker-compose up` in the root folder of this repo

**Comment by juniur** [comment]
how to do it? im not familiar with docker. thanks
