### ISSUE TITLE
compose-angular-contacts-app-example

### ISSUE THREAD

**Issue by juniur** [avatsaev/angular-contacts-app-example#14]
how to do it? im not familiar with docker. im using windows. in your package.json file no docker and docker-compose. i think there's something wrong of your changes. docker-compose up not recognized.

**Comment by avatsaev** [comment]
I don't know how to use Docker on Windows, I use Mac/Linux, did you change the environment.ts file 

you need to change 

`baseUrl: 'http://localhost:8080/api/'`
to
`baseUrl: 'http://localhost:3000/api/'`

**Comment by avatsaev** [comment]
I don't know how to run Docker on Windows, I use Linux/Mac

I've pushed a new update to the api repo to change the port from 3000 to 8080 like in docker, download it and try again, you don't need docker, just need to match the server port to the same port as in environment.ts file in the angular app

**Comment by juniur** [comment]
i got it! i was able to run now the contact app with data on the browser. thanks.
