### ISSUE TITLE
repository avatsaev/angular-contacts-api not found: does not exist or no pull access

### ISSUE THREAD

**Issue by yuren1978** [avatsaev/angular-contacts-app-example#15]
When I try to run command  "docker-compose up", I got the error : repository avatsaev/angular-contacts-api not found: does not exist or no pull access.

**Comment by avatsaev** [comment]
Sorry it was private by default for some reason, made it public, so you should be able to pull now without any problems

**Comment by yuren1978** [comment]
working now. Thanks.
