### ISSUE TITLE
Did you intend to remove docker support?

### ISSUE THREAD

**Issue by amirtoole** [avatsaev/angular-contacts-app-example#19]
Dockerfile, docker-compose.yml were removed in this commit: https://github.com/avatsaev/angular-contacts-app-example/commit/2796b400c939391592302e4acc9cd05a6b017bb6

Not sure if accidentally removed or not, but docker is still referenced in latest README

**Comment by avatsaev** [comment]
Sorry I needed to update the whole Docker thing to use Angular CLI's new Workspaces workflow.

This commit adds docker support: https://github.com/avatsaev/angular-contacts-app-example/commit/878de465c11036cf9318b052a6e56db73454ac01

Should work fine, let me know if it worked for you
