### ISSUE TITLE
ContactsActionTypes.CREATE

### ISSUE THREAD

**Issue by JoseRFJuniorLLMs** [avatsaev/angular-contacts-app-example#20]
Does this project save everything local then send it to api?

**Comment by avatsaev** [comment]
Sends to API, but DEMO remote API is temporary disabled.

You can host an API yourself using this repository: https://github.com/avatsaev/angular-contacts-app-example-api


Or you can run everything at once (client+api+db) with Docker Compose from this repository, refer to README.md
