### ISSUE TITLE
Reducer error 

### ISSUE THREAD

**Issue by mehdirajani5** [avatsaev/angular-contacts-app-example#29]
`property payload does not exist on all type. `

**Comment by mehdirajani5** [comment]
![Screenshot from 2019-03-29 23-00-35](https://user-images.githubusercontent.com/17649381/55254021-ab007d80-5278-11e9-8027-9d32f805c1d5.png)
![Screenshot from 2019-03-29 23-07-40](https://user-images.githubusercontent.com/17649381/55254022-ab991400-5278-11e9-887c-1706df9aeac2.png)

**Comment by avatsaev** [comment]
Must remove destructuring and use `action` parameter instead

**Comment by mehdirajani5** [comment]
I have created this issue and also create PR shortly.
