### ISSUE TITLE
Unable to add contact in Demo

### ISSUE THREAD

**Issue by denspiro** [avatsaev/angular-contacts-app-example#36]
**Describe the bug**
Unable to add a contact in [Demo](https://angular-contacts-ngrx.surge.sh)

**To Reproduce**
1. Go to 'https://angular-contacts-ngrx.surge.sh'
2. Click on '+new'
3. Fill the form
4. Submit a form
5. The contact list is still empty

**Expected behavior**
The contact list should be populated with added contact.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome 
 - Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by avatsaev** [comment]
The backend server is out, everything should work if your run it locally

**Comment by denspiro** [comment]
Thanks! Closing it.
